  
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
  namespace: flux-system
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    requests.storage: "0"
    limits.cpu: "2"
    limits.memory: 2Gi
    persistentvolumeclaims: "0"
    services.loadbalancers: "0"
    services.nodeports: "0"
    deployments.apps: "2"
    services: "4"
    pods: "8"