  
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
  namespace: flux-system
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    requests.storage: "0"
    limits.cpu: "2"
    limits.memory: 2Gi
    count/persistentvolumeclaims: "0"
    count/services.loadbalancers: "0"
    count/services.nodeports: "0"
    count/deployments.apps: "2"
    count/services: "4"
    count/pods: "8"