  
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
spec:
  hard:
    requests.cpu: "0"
    requests.memory: 0Gi
    requests.storage: "0"
    limits.cpu: "0"
    limits.memory: 0Gi
    persistentvolumeclaims: "0"
    services.loadbalancers: "0"
    services.nodeports: "0"
    deployments.apps: "0"
    services: "0"
    pods: "0"