  
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
spec:
  hard:
    requests.cpu: 9500m
    requests.memory: 10000Mi
    requests.storage: "0"
    limits.cpu: "20"
    limits.memory: 10000Mi
    count/persistentvolumeclaims: "0"
    count/services.loadbalancers: "0"
    count/services.nodeports: "0"
    count/deployments.apps: "1"
    count/daemonsets.apps: "5"
    count/services: "1"
    count/pods: "100"