  
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
spec:
  hard:
    requests.cpu: 7500m
    requests.memory: 5000Mi
    requests.storage: "0"
    limits.cpu: "20"
    limits.memory: 10000Mi
    count/persistentvolumeclaims: "0"
    count/services.loadbalancers: "0"
    count/services.nodeports: "0"

    # osm-controller
    count/deployments.apps: "1"
            
    # csi-secrets-store, csi-secrets-store-provider-azure
    # dummy-av, dummy-fim
    # kured
    count/daemonsets.apps: "5"

    # osm-controller+validator
    count/services: "2"

    # csi-secrets-store (3*[oos nodepood nodes] + 3*[ins nodepool nodes] = 12)
    # csi-secrets-store-provider-azure (1*[oos nodepood nodes] + 1*[ins nodepool nodes] = 4)
    # dummy-av (1*[all nodes] = 7)
    # dummy-fim (1*[all nodes] = 7)
    # kured (1*[all nodes] = 7)
    # osm-controller (1 = 1)
    # x~1.5 for scale out / rolling upgrades
    count/pods: "60"