apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster-baseline-settings
resources:
- namespace.yaml
- resource-quota.yaml
- networkpolicy-denyall.yaml
- limit-range.yaml
- rbac.yaml