apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster-baseline-settings
resources:
- osm-crds.yaml
- osm.yaml

secretGenerator:
  - name: osm-acr-instance
    type: Opaque
    literals:
      - name=REPLACE_ME_WITH_YOUR_ACRNAME

images:
- name: docker.io/openservicemesh/osm-controller
  newName: REPLACE_ME_WITH_YOUR_ACRNAME.azurecr.io/openservicemesh/osm-controller
